# --- AWS DynamoDB ---
quarkus.dynamodb.aws.region=eu-west-3
quarkus.dynamodb.devservices.enabled=false

# --- AI Gemini Config ---
gemini.api.key=${GEMINI_API_KEY:NO_KEY}
quarkus.rest-client.gemini-api.url=https://generativelanguage.googleapis.com
gemini.model.chat=gemini-2.0-flash
gemini.model.embedding=gemini-embedding-001
gemini.api.version=v1beta

# --- Quarkus Lambda ---
# Le CORS est géré par CorsFilter.kt
