quarkus.http.port=8080
quarkus.lambda.handler=io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
quarkus.package.type=fast-jar

# --- DynamoDB ---
quarkus.dynamodb.devservices.enabled=false
quarkus.dynamodb.aws.region=eu-west-3