quarkus.http.port=8080
quarkus.lambda.handler=io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
quarkus.package.type=fast-jar

# --- CORS ---
quarkus.http.cors=true
quarkus.http.cors.origins=https://ezzium.fr,https://www.ezzium.fr,http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# --- DynamoDB ---
quarkus.dynamodb.devservices.enabled=false
quarkus.dynamodb.aws.region=eu-west-3