name: Build & Deploy Quarkus Lambda

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-west-3
  LAMBDA_FUNCTION_NAME: smarttrack-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 🧱 Build du projet Quarkus pour Lambda
      - name: Build Quarkus Lambda JAR
        run: |
          mvn clean package -DskipTests \
            -Dquarkus.package.type=uber-jar

      # ⚙️ Configuration des credentials AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 🚀 Déploiement de la fonction Lambda
      - name: Deploy to AWS Lambda
        run: |
          JAR_FILE="target/smarttrack-1.0.0-SNAPSHOT-runner.jar"
          echo "Deploying $JAR_FILE to Lambda function: ${{ env.LAMBDA_FUNCTION_NAME }}"
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://$JAR_FILE