name: Build & Deploy Lambda

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-west-3
  LAMBDA_FUNCTION_NAME: smarttrack-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (shade/repackage)
        run: mvn clean package -DskipTests

      # ⚡ Configure AWS creds
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ⚡ Déploiement Lambda (update uniquement)
      - name: Update Lambda function code
        run: |
          JAR_FILE="target/smarttrack-0.0.1-SNAPSHOT.jar"
          echo "Deploying $JAR_FILE to smarttrack-api ..."
          aws lambda update-function-code \
            --function-name smarttrack-api \
            --zip-file fileb://$JAR_FILE